# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: Build
        run: |-
          cd server
          go build -v ./...
  lint:
    runs-on: ubuntu-latest
    # ensure the code builds before trying to lint it
    needs: ["build"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: server
  docker:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build server/ --tag jacobmichels/computer_nerd
      - name: Push image
        run: docker push jacobmichels/computer_nerd
