name: frontend-CI

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"

  pull_request:
    branches: ["main"]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CD workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: frontend_deploy_trigger
